apiVersion: v1
kind: Service
metadata:
  labels:
    run: flower-shop-int
  name: flower-shop-int
spec:
  ports:
  - name: flower-shop-int
    port: 443
    protocol: TCP
  selector:
    run: flower-shop
